export const ROSTER_SLOTS = {
  NFL: [
    {
      key: '66_1',
      position: 'QB',
      slotId: 66,
      required: true,
      controlType: 'text',
      eligiblePositions: ['QB'],
    },
    {
      key: '67_1',
      position: 'RB',
      slotId: 67,
      required: true,
      controlType: 'text',
      eligiblePositions: ['RB'],
    },
    {
      key: '67_2',
      position: 'RB',
      slotId: 67,
      required: true,
      controlType: 'text',
      eligiblePositions: ['RB'],
    },
    {
      key: '68_1',
      position: 'WR',
      slotId: 68,
      required: true,
      controlType: 'text',
      eligiblePositions: ['WR'],
    },
    {
      key: '68_2',
      position: 'WR',
      slotId: 68,
      required: true,
      controlType: 'text',
      eligiblePositions: ['WR'],
    },
    {
      key: '68_3',
      position: 'WR',
      slotId: 68,
      required: true,
      controlType: 'text',
      eligiblePositions: ['WR'],
    },
    {
      key: '69_1',
      position: 'TE',
      slotId: 69,
      required: true,
      controlType: 'text',
      eligiblePositions: ['TE'],
    },
    {
      key: '70_1',
      position: 'FLEX',
      slotId: 70,
      required: true,
      controlType: 'text',
      eligiblePositions: ['RB', 'WR', 'TE'],
    },
    {
      key: '71_1',
      position: 'DST',
      slotId: 71,
      required: true,
      controlType: 'text',
      eligiblePositions: ['DST'],
    },
  ],
  CFB: [
    {
      key: '504_1',
      position: 'QB',
      slotId: 504,
      required: true,
      controlType: 'text',
      eligiblePositions: ['QB'],
    },
    {
      key: '505_1',
      position: 'RB',
      slotId: 505,
      required: true,
      controlType: 'text',
      eligiblePositions: ['RB'],
    },
    {
      key: '505_2',
      position: 'RB',
      slotId: 505,
      required: true,
      controlType: 'text',
      eligiblePositions: ['RB'],
    },
    {
      key: '506_1',
      position: 'WR',
      slotId: 506,
      required: true,
      controlType: 'text',
      eligiblePositions: ['WR'],
    },
    {
      key: '506_2',
      position: 'WR',
      slotId: 506,
      required: true,
      controlType: 'text',
      eligiblePositions: ['WR'],
    },
    {
      key: '506_3',
      position: 'WR',
      slotId: 506,
      required: true,
      controlType: 'text',
      eligiblePositions: ['WR'],
    },
    {
      key: '507_1',
      position: 'FLEX',
      slotId: 507,
      required: true,
      controlType: 'text',
      eligiblePositions: ['RB', 'WR'],
    },
    {
      key: '508_1',
      position: 'S-FLEX',
      slotId: 508,
      required: true,
      controlType: 'text',
      eligiblePositions: ['QB', 'RB', 'WR'],
    },
  ],
  CFL: [
    {
      key: '124_1',
      position: 'QB',
      slotId: 124,
      required: true,
      controlType: 'text',
      eligiblePositions: [],
    },
    {
      key: '125_1',
      position: 'RB',
      slotId: 125,
      required: true,
      controlType: 'text',
      eligiblePositions: ['127_1', '127_2'],
    },
    {
      key: '126_1',
      position: 'WR',
      slotId: 126,
      required: true,
      controlType: 'text',
      eligiblePositions: ['126_2', '127_1', '127_2'],
    },
    {
      key: '126_2',
      position: 'WR',
      slotId: 126,
      required: true,
      controlType: 'text',
      eligiblePositions: ['126_1', '127_1', '127_2'],
    },
    {
      key: '127_1',
      position: 'FLEX',
      slotId: 127,
      required: true,
      controlType: 'text',
      eligiblePositions: ['125_1', '126_1', '126_2', '127_2'],
    },
    {
      key: '127_2',
      position: 'FLEX',
      slotId: 127,
      required: true,
      controlType: 'text',
      eligiblePositions: ['125_1', '126_1', '126_2', '127_1'],
    },
    {
      key: '128_1',
      position: 'DST',
      slotId: 128,
      required: true,
      controlType: 'text',
      eligiblePositions: [],
    },
  ],
}

export const FLEX_SLOTS = {
  NFL: [70],
  CFL: [127],
  CFB: [507, 508],
}
