export interface Passing {
  accuracy_percent: number
  aimed_passes: number
  attempts: number
  avg_depth_of_target: number
  avg_time_to_throw: number
  bats: number
  big_time_throws: number
  btt_rate: number
  completion_percent: number
  completions: number
  declined_penalties: number
  def_gen_pressures: number
  drop_rate: number
  dropbacks: number
  drops: number
  first_downs: number
  franchise_id: number
  grades_hands_fumble: number
  grades_offense: number
  grades_pass: number
  grades_run: number
  hit_as_threw: number
  interceptions: number
  lastUpdated: string
  passing_snaps: number
  penalties: number
  player: string
  player_game_count: number
  player_id: number
  position: string
  pressure_to_sack_rate: number
  qb_rating: number
  sack_percent: number
  sacks: number
  scrambles: number
  spikes: number
  stat_type: string
  team_name: string
  thrown_aways: number
  touchdowns: number
  turnover_worthy_plays: number
  twp_rate: number
  yards: number
  ypa: number
  _id: string
}
