export interface ReceivingStats {
  avg_depth_of_target: number
  avoided_tackles: number
  caught_percent: number
  contested_catch_rate: number
  contested_receptions: number
  contested_targets: number
  declined_penalties: number
  drop_rate: number
  drops: number
  first_downs: number
  franchise_id: number
  fumbles: number
  grades_hands_drop: number
  grades_hands_fumble: number
  grades_offense: number
  grades_pass_block: number | null
  grades_pass_route: number
  inline_rate: number
  inline_snaps: number
  interceptions: number
  lastUpdated: string
  longest: number
  pass_block_rate: number
  pass_blocks: number
  pass_plays: number
  penalties: number
  player: string
  player_game_count: number
  player_id: number
  position: string
  receptions: number
  route_rate: number
  routes: number
  slot_rate: number
  slot_snaps: number
  stat_type: string
  targeted_qb_rating: number
  targets: number
  team_name: string
  touchdowns: number
  wide_rate: number
  wide_snaps: number
  yards: number
  yards_after_catch: number
  yards_after_catch_per_reception: number
  yards_per_reception: number
  yprr: number
  __v: number
  _id: string
}
