export interface RushingStats {
  attempts: number
  avoided_tackles: number
  breakaway_attempts: number
  breakaway_percent: number
  breakaway_yards: number
  declined_penalties: number
  designed_yards: number
  drops: number
  elu_recv_mtf: number
  elu_rush_mtf: number
  elu_yco: number
  elusive_rating: number
  explosive: number
  first_downs: number
  franchise_id: number
  fumbles: number
  gap_attempts: number
  grades_hands_fumble: number
  grades_offense: number
  grades_offense_penalty: number
  grades_pass: number | null
  grades_pass_block: number | null
  grades_pass_route: number
  grades_run: number
  grades_run_block: number
  lastUpdated: string
  longest: number
  penalties: number
  player: string
  player_game_count: number
  player_id: number
  position: string
  rec_yards: number
  receptions: number
  routes: number
  run_plays: number
  scramble_yards: number
  scrambles: number
  stat_type: string
  targets: number
  team_name: string
  total_touches: number
  touchdowns: number
  yards: number
  yards_after_contact: number
  yco_attempt: number
  ypa: number
  yprr: number
  zone_attempts: number
  __v: number
  _id: string
}
